<?php

namespace oihana\exceptions\http ;

/**
 * The HTTP 511 Network Authentication Required server error response status code indicates that the client
 * needs to authenticate to gain network access. This status is not generated by origin servers, but by
 * intercepting proxies that control access to the network (for example, captive portals).
 *
 * @package oihana\exceptions\http
 * @author  Marc Alcaraz (ekameleon)
 * @since   1.0.0
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/511
 */
class Error511 extends HttpException
{
    public const int    DEFAULT_CODE    = 511 ;
    public const string DEFAULT_MESSAGE = 'Network Authentication Required (511)' ;
}
